#!/bin/sh
# Copyright (C) 2009-2016  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

# Comm : Generation d'une partie CasCade fictive

rm   -rf nokas
mkdir -p nokas
cp  HexDummyCad.hxx nokas/

while read fic
      do
      echo '#include "HexDummyCad.hxx"' > nokas/$fic
      done << END_OF_FILE
BRepAdaptor_Curve.hxx
BRepAlgoAPI_Section.hxx
BRepBuilderAPI_MakeEdge.hxx
BRepBuilderAPI_MakeVertex.hxx
BRepBuilderAPI_Transform.hxx
BRepPrimAPI_MakeCylinder.hxx
BRepPrimAPI_MakeSphere.hxx
BRepTools.hxx
BRep_Builder.hxx
BRep_Tool.hxx
GCPnts_AbscissaPoint.hxx
GC_MakeCircle.hxx
GeomAPI_ProjectPointOnCurve.hxx
Geom_Circle.hxx
TopExp_Explorer.hxx
TopTools_IndexedMapOfShape.hxx
TopoDS.hxx
TopoDS_Compound.hxx
TopoDS_Edge.hxx
TopoDS_Iterator.hxx
TopoDS_Shape.hxx
TopoDS_Vertex.hxx
gp_Circ.hxx
gp_Dir.hxx
gp_Lin.hxx
gp_Pln.hxx
gp_Pnt.hxx
END_OF_FILE
