#!/bin/sh
# Comm : Sauvegarde

model=`pwd`
model=`basename $model`
saved=motor_saved
saved=saved_motor

umake -clean
touch _____________________________
cd ..
mkdir -p $saved
###   ./$model/dsave $* -ln internal_doc implem model -d $saved
./$model/dsave $model -d $saved
