#!/bin/sh
# Copyright (C) 2009-2013  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

# Comm : Makefile associe aux tests unitaires

commande=$0
liste_args="$*"

# =============================================== Begin

test_u=
opt=
for arg in $*
   do
   case $arg in
      -setx ) set -x 
           ;;
      -clean  ) 
         rm -rf *.exe *.a *.o *.bak *.brep *~ *.vtk *.cpp *.xml *.exe.stackdump
           exit
           ;;
      -j  ) opt="$opt -j4"
           ;;
      -j* ) opt="$opt $arg"
           ;;
      -k  ) echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo
            echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo ; echo
           ;;
      *) if ( [ -z "$test_u" ] ) then
            test_u=`echo $arg | cut -d. -f1`
            ishere=`grep -w $test_u test_*.cxx | grep -c tabargs`
            if ( [ "$ishere" = "0" ] ) then
               echo "****"
               echo "**** Programme non trouve : $test_u"
               echo "****"
               exit 1
               fi
            fi
   esac
   done

if ( [ -z "$test_u" ] ) then
   test_u=test_hexa
   fi

if ( [ ! -f makefile.ozz ] ) then
   ./make.make
   fi

make -f makefile.ozz $opt main=$test_u
